# Generated by Django 3.0 on 2019-12-03 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DMTable',
            fields=[
                ('dmtable_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('dmtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmtablePlayer', to='dm_app.DMTable')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('npc_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('hp', models.CharField(max_length=255)),
                ('ac', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('dmtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmtableNPC', to='dm_app.DMTable')),
            ],
        ),
        migrations.AddField(
            model_name='dmtable',
            name='userdmtable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userdmtable', to='dm_app.User'),
        ),
    ]
