# Generated by Django 3.0 on 2019-12-02 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('notes', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='dm_app.User')),
            ],
        ),
    ]
