# Generated by Django 3.0 on 2019-12-02 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dm_app', '0002_dmtable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('dmtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmtablePlayer', to='dm_app.DMTable')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hp', models.CharField(max_length=255)),
                ('ac', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('dmtable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmtableNPC', to='dm_app.DMTable')),
            ],
        ),
    ]
